spring:
  application:
    name: app-back-end-identity

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:to-teacher-identity}

server:
  port: ${SERVER_PORT:8081}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
