package web.tosunsaeng.identity.domain.user.domain.enums;

public enum UserWithdrawalCleanupStatus {
	EXTERNAL_CLEANUP_PENDING,
	EXTERNAL_CLEANUP_IN_PROGRESS,
	EXTERNAL_CLEANUP_RETRY_WAIT,
	EXTERNAL_CLEANUP_COMPLETED,
	IDENTITY_RELEASE_PENDING,
	CLEANED,
	RECONCILIATION_REQUIRED;

	public boolean canTransitionTo(UserWithdrawalCleanupStatus next) {
		return switch (this) {
			case EXTERNAL_CLEANUP_PENDING -> next == EXTERNAL_CLEANUP_IN_PROGRESS;
			case EXTERNAL_CLEANUP_IN_PROGRESS -> next == EXTERNAL_CLEANUP_RETRY_WAIT
					|| next == EXTERNAL_CLEANUP_COMPLETED
					|| next == RECONCILIATION_REQUIRED;
			case EXTERNAL_CLEANUP_RETRY_WAIT -> next == EXTERNAL_CLEANUP_IN_PROGRESS;
			case EXTERNAL_CLEANUP_COMPLETED -> next == IDENTITY_RELEASE_PENDING;
			case IDENTITY_RELEASE_PENDING -> next == CLEANED
					|| next == RECONCILIATION_REQUIRED;
			case CLEANED, RECONCILIATION_REQUIRED -> false;
		};
	}
}
